### ISSUE TITLE
Cannot log back in to app after revoking access

### ISSUE THREAD

**Issue by lupomancer** [thilobillerbeck/skymoth#2]
I revoked access to the app from my instance in an effort to get Skymoth to stop reposting my mastodon posts to BSKY. Now when I try to log in to Skymoth, my instance throws me the following error:

“ Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.”

i believe it’s rated to the following issue:

https://github.com/mastodon/mastodon/issues/27740

**Comment by thilobillerbeck** [comment]
Thx for reporting, I'll have a look into that :)

**Comment by thilobillerbeck** [comment]
this slipped kind of under my radar, I will finally hwave a look at this, sorry

**Comment by thilobillerbeck** [comment]
Since this bug seems to have been fixed on Mastodons side, I introduced a cleanup job which removes accounts with broken Mastodon tokens and instances without any users. (https://github.com/thilobillerbeck/skymoth/commit/c10fa9f4ebce476fc6b20f2484a10a71b91b33a6) Due to how things work with OAuth I cannot create new creds myself, but this can be seen as a self healing process and should hopefully prevent thos kinds of states in the future.
