### ISSUE TITLE
Could not remove my data

### ISSUE THREAD

**Issue by alroniks** [thilobillerbeck/skymoth#20]
**Describe the bug**

Hello @thilobillerbeck 

I've tried to remove my data using special link, but it does not work.

Error message is:

```
Invalid `prisma.user.delete()` invocation:\n\n\nForeign key constraint violated: `Repost_userId_fkey (index)`
```

**To Reproduce**
1. Go to https://skymoth.app
2. Click on 'here' link in the sentence "If you want to delete your account, you can do so here."
3. See error

**Expected behavior**
My data removed

**Comment by thilobillerbeck** [comment]
That's not good, I'll have a look.

**Comment by thilobillerbeck** [comment]
fyi. I'll be back home from a trip tonight so I'll fix this the following days

**Comment by thilobillerbeck** [comment]
Since this bug seems to have been fixed on Mastodons side, I introduced a cleanup job which removes accounts with broken Mastodon tokens and instances without any users. (https://github.com/thilobillerbeck/skymoth/commit/c10fa9f4ebce476fc6b20f2484a10a71b91b33a6) Due to how things work with OAuth I cannot create new creds myself, but this can be seen as a self healing process and should hopefully prevent thos kinds of states in the future.

**Comment by alroniks** [comment]
Thank you @thilobillerbeck 

I've just tried, seems it works! 🎉

**Comment by thilobillerbeck** [comment]
> Thank you @thilobillerbeck 
> 
> I've just tried, seems it works! 🎉

Perfect. I'll close this then. :)
